name: 02 - Workflow Events
on: workflow_dispatch:            
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger name
              run: echo "workflow was triggered by ${{github.event_name}}"
    
